const C=window.BHETINCHHA_CONFIG;const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let session=JSON.parse(sessionStorage.getItem('bh_session')||'null');
async function api(action,payload={}){if(!C.API_URL||C.DEMO_MODE)return demo(action,payload);return fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:session?.token,...payload})}).then(r=>r.json())}
function demo(action,p){if(action==='login')return Promise.resolve({ok:true,token:'demo-token',user:{name:'Demo Super Admin',role:'SUPER_ADMIN',permissions:['*']}});if(action==='adminDashboard')return Promise.resolve({ok:true,kpi:{businesses:128,pending:14,admins:4,activePlans:72},admins:[{id:'A01',name:'Supplier Admin',username:'supplier',active:true,permissions:['BUSINESS_VIEW','BUSINESS_EDIT']},{id:'A02',name:'Emergency Admin',username:'emergency',active:false,permissions:['EMERGENCY_VIEW']}],pending:[{id:'B100',name:'Kathmandu Taxi Service',category:'Taxi Service',plan:'Professional'},{id:'B101',name:'ABC Solar',category:'Solar & Battery',plan:'Basic'}],audit:[{time:'2026-08-26 15:30',actor:'Super Admin',action:'ADMIN_PERMISSION_UPDATE',record:'A01'}]});return Promise.resolve({ok:true})}
function showApp(){location.href='admin.html'}
async function login(){const username=$('#username').value.trim(),password=$('#password').value;const r=await api('login',{username,password});if(!r.ok)return $('#loginMsg').textContent=r.message||'Login failed';session={token:r.token,user:r.user};sessionStorage.setItem('bh_session',JSON.stringify(session));showApp()}
function guard(){if(!session){location.href='admin-login.html';return false}$('#who').textContent=`${session.user.name} • ${session.user.role}`;return true}
async function loadDashboard(){if(!guard())return;const r=await api('adminDashboard');if(!r.ok){alert(r.message||'Access denied');return}const k=r.kpi||{};$('#kpis').innerHTML=[['Businesses',k.businesses||0],['Pending Approval',k.pending||0],['Admins',k.admins||0],['Paid Active',k.activePlans||0]].map(x=>`<div class="card kpi"><span class="muted">${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#adminsRows').innerHTML=(r.admins||[]).map(a=>`<tr><td>${a.name}</td><td>${a.username}</td><td>${a.active?'Active':'Inactive'}</td><td>${a.permissions.join(', ')}</td><td><button class="btn btn-outline" onclick="toggleAdmin('${a.id}',${!a.active})">${a.active?'Inactive':'Activate'}</button></td></tr>`).join('');$('#pendingRows').innerHTML=(r.pending||[]).map(b=>`<tr><td>${b.name}</td><td>${b.category}</td><td>${b.plan}</td><td><button class="btn btn-success" onclick="approveBusiness('${b.id}')">Approve</button> <button class="btn btn-outline">Review</button></td></tr>`).join('');$('#auditRows').innerHTML=(r.audit||[]).map(a=>`<tr><td>${a.time}</td><td>${a.actor}</td><td>${a.action}</td><td>${a.record}</td></tr>`).join('')}
async function toggleAdmin(id,active){if(!confirm(`Admin ${active?'activate':'inactive'} गर्ने?`))return;const r=await api('setAdminActive',{id,active});alert(r.ok?'Updated':'Failed');loadDashboard()}
async function approveBusiness(id){if(!confirm('Business approve गर्ने? Verification details review गरिसक्नुभएको छ?'))return;const r=await api('approveBusiness',{id});alert(r.ok?'Approved':'Failed');loadDashboard()}
function logout(){sessionStorage.removeItem('bh_session');location.href='admin-login.html'}
document.addEventListener('DOMContentLoaded',()=>{if($('#loginBtn'))$('#loginBtn').onclick=login;if($('#kpis'))loadDashboard();$('#logoutBtn')&&($('#logoutBtn').onclick=logout)});
