const C=window.BHETINCHHA_CONFIG,D=window.BHETINCHHA_DATA;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function api(action,payload={}){if(!C.API_URL||C.DEMO_MODE)return Promise.resolve({ok:true,demo:true});return fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})}).then(r=>r.json());}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function renderCategories(){const el=$('#categories');if(!el)return;el.innerHTML=D.masterCategories.map(c=>`<button class="card cat-card" data-cat="${esc(c.id)}"><div class="cat-icon">${c.icon}</div><h3>${esc(c.name)}</h3><div class="muted">${c.subs.slice(0,3).map(esc).join(' • ')}</div></button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{$('#q').value=b.dataset.cat==='transport'?'Taxi Service':b.textContent.trim();doSearch();});}
function businessCard(b){return `<article class="card business"><div class="meta">${b.verified?'<span class="badge success">✓ Verified</span>':'<span class="badge warning">Review pending</span>'}${b.premium?'<span class="badge">★ Premium</span>':''}</div><h3>${esc(b.name)}</h3><div class="muted">${esc(b.category)} • ${esc(b.location)}</div><p>${esc(b.desc||'')}</p><div class="actions"><a class="btn btn-primary" href="tel:${esc(b.phone)}">📞 Call</a><a class="btn btn-outline" target="_blank" rel="noopener" href="https://wa.me/977${esc(String(b.whatsapp||b.phone).replace(/\D/g,'').slice(-10))}">💬 WhatsApp</a></div></article>`}
async function doSearch(){const q=($('#q')?.value||'').trim(),location=($('#location')?.value||'').trim();let list=D.demoBusinesses;if(C.API_URL&&!C.DEMO_MODE){const r=await api('publicSearch',{q,location});if(r.ok&&Array.isArray(r.items))list=r.items;}if(q)list=list.filter(x=>(x.name+' '+x.category+' '+x.desc).toLowerCase().includes(q.toLowerCase()));if(location)list=list.filter(x=>x.location.toLowerCase().includes(location.toLowerCase()));const out=$('#results');out.innerHTML=list.length?list.map(businessCard).join(''):'<div class="card full">कुनै नतिजा भेटिएन । अर्को शब्द वा स्थानबाट खोज्नुहोस् ।</div>';out.scrollIntoView({behavior:'smooth',block:'start'});}
function openModal(id){$('#'+id)?.classList.add('open');document.body.style.overflow='hidden'}function closeModal(id){$('#'+id)?.classList.remove('open');document.body.style.overflow=''}
let regStep=1,reg={plan:'basic'};
function setStep(n){regStep=n;$$('.reg-step').forEach((x,i)=>x.hidden=i!==n-1);$$('.step').forEach((x,i)=>x.classList.toggle('active',i===n-1));$('#regBack').hidden=n===1;$('#regNext').textContent=n===4?'Submit for Review':'Next';}
function collect(){$$('#businessForm [name]').forEach(e=>reg[e.name]=e.value);const checked=$$('input[name="categoryPick"]:checked').map(x=>x.value);if(checked.length)reg.categories=checked;}
async function nextReg(){collect();if(regStep<4){setStep(regStep+1);return}const r=await api('registerBusiness',{business:reg});alert(r.ok?'Registration received. Admin review पछि listing active हुनेछ ।':'Submit failed');if(r.ok)closeModal('businessModal')}
function buildRegister(){const cats=D.masterCategories.flatMap(c=>c.subs).slice(0,80);$('#categoryPicks').innerHTML=cats.map(x=>`<label><input type="checkbox" name="categoryPick" value="${esc(x)}"> ${esc(x)}</label>`).join('<br>');$('#plans').innerHTML=D.plans.slice(1).map(p=>`<button type="button" class="plan ${p.id==='basic'?'selected':''}" data-plan="${p.id}"><strong>${p.name}</strong><div class="price">रु ${p.price.toLocaleString()}</div><div class="muted">/${p.period}</div><ul>${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></button>`).join('');$$('[data-plan]').forEach(x=>x.onclick=()=>{$$('[data-plan]').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');reg.plan=x.dataset.plan});}
function init(){renderCategories();buildRegister();$('#searchBtn').onclick=doSearch;$('#q').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});$$('[data-open-register]').forEach(x=>x.onclick=()=>openModal('businessModal'));$$('[data-close]').forEach(x=>x.onclick=()=>closeModal(x.dataset.close));$('#regNext').onclick=nextReg;$('#regBack').onclick=()=>setStep(Math.max(1,regStep-1));$('#policeBtn').onclick=()=>window.open(C.OFFICIAL_POLICE_URL,'_blank','noopener');$('#sosBtn').onclick=()=>openModal('sosModal');$('#sendSOS').onclick=()=>alert('Prototype: emergency category + location will be routed to verified responders/admin. Official emergency calls remain primary.');doSearch();}
document.addEventListener('DOMContentLoaded',init);
