const C=window.BHETINCHHA_CONFIG,D=window.BHETINCHHA_DATA;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function api(action,payload={}){if(!C.API_URL||C.DEMO_MODE)return Promise.resolve({ok:true,demo:true});return fetch(C.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})}).then(r=>r.json());}
let currentResults=[];
function renderCategories(){const el=$('#categories');if(!el)return;el.innerHTML=D.masterCategories.map(c=>`<button class="card cat-card" data-cat="${esc(c.id)}"><div class="cat-icon">${c.icon}</div><h3>${esc(c.name)}</h3><div class="muted">${c.subs.slice(0,4).map(esc).join(' • ')}</div></button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{const c=D.masterCategories.find(x=>x.id===b.dataset.cat);$('#q').value=c?.subs?.[0]||c?.name||'';doSearch();});}
function businessCard(b){const sponsored=b.premium?'<span class="sponsored-label">Sponsored</span>':'';return `<article class="card business ${b.premium?'sponsored':''}">${sponsored}<div class="meta">${b.verified?'<span class="badge success">✓ Verified</span>':'<span class="badge warning">Not verified</span>'}${b.premium?'<span class="badge">★ Featured</span>':''}</div><h3><button class="profile-link" data-profile="${esc(b.id)}">${esc(b.name)}</button></h3><div class="muted">${esc(b.category||'Business / Service')} • 📍 ${esc(b.location||'Nepal')}</div><p>${esc(b.desc||'')}</p><div class="view-count">👁 ${Number(b.views||0).toLocaleString()} profile views</div><div class="actions"><button class="btn btn-outline" data-profile="${esc(b.id)}">विवरण</button>${b.phone?`<a class="btn btn-primary" href="tel:${esc(b.phone)}">📞 Call</a>`:''}${(b.whatsapp||b.phone)?`<a class="btn btn-outline" target="_blank" rel="noopener" href="https://wa.me/977${esc(String(b.whatsapp||b.phone).replace(/\D/g,'').slice(-10))}">💬 WhatsApp</a>`:''}</div></article>`}
function bindProfiles(){$$('[data-profile]').forEach(x=>x.onclick=()=>showProfile(x.dataset.profile));}
function sortAndRender(){let list=[...currentResults],sort=$('#sortResults')?.value||'relevance';if(sort==='verified')list.sort((a,b)=>Number(!!b.verified)-Number(!!a.verified)||Number(!!b.premium)-Number(!!a.premium));if(sort==='name')list.sort((a,b)=>String(a.name).localeCompare(String(b.name)));const out=$('#results');out.innerHTML=list.length?list.map(businessCard).join(''):'<div class="card full">कुनै नतिजा भेटिएन । अर्को शब्द वा स्थानबाट खोज्नुहोस् ।</div>';bindProfiles();}
async function doSearch(){const q=($('#q')?.value||'').trim(),location=($('#location')?.value||'').trim();$('#resultSummary').textContent='खोज्दै...';let list=[];try{if(C.API_URL&&!C.DEMO_MODE){const r=await api('publicSearch',{q,location});if(r.ok&&Array.isArray(r.items))list=r.items;}else list=D.demoBusinesses;}catch(e){list=D.demoBusinesses;}
if((!C.API_URL||C.DEMO_MODE)&&q)list=list.filter(x=>(x.name+' '+x.category+' '+x.desc).toLowerCase().includes(q.toLowerCase()));if((!C.API_URL||C.DEMO_MODE)&&location)list=list.filter(x=>String(x.location).toLowerCase().includes(location.toLowerCase()));currentResults=list;$('#resultSummary').textContent=`${list.length} नतिजा${q?' • '+q:''}${location?' • '+location:''}`;sortAndRender();if(q||location)$('#search-results').scrollIntoView({behavior:'smooth',block:'start'});}
async function showProfile(id){let b=currentResults.find(x=>String(x.id)===String(id))||D.demoBusinesses.find(x=>x.id===id);try{if(C.API_URL&&!C.DEMO_MODE){const r=await api('publicBusinessDetail',{id});if(r.ok&&r.item)b=r.item;}}catch(e){}if(!b)return;$('#profileContent').innerHTML=`<div class="profile-cover"><div>${b.verified?'✓ Verified Business':'Business Profile'} ${b.premium?' • ★ Featured':''}</div><h2>${esc(b.name)}</h2><div>📍 ${esc(b.location||'Nepal')}</div></div><div class="profile-grid"><div class="card"><h3>व्यवसायबारे</h3><p>${esc(b.desc||'विवरण उपलब्ध छैन ।')}</p><div class="info-list"><div class="info-row"><strong>Category:</strong> ${esc(b.category||'')}</div><div class="info-row"><strong>ठेगाना:</strong> ${esc(b.address||b.location||'')}</div>${b.website?`<div class="info-row"><strong>Website:</strong> ${esc(b.website)}</div>`:''}<div class="info-row">👁 ${Number(b.views||0).toLocaleString()} views</div></div></div><div class="card"><h3>सम्पर्क</h3><div class="actions">${b.phone?`<a class="btn btn-primary" href="tel:${esc(b.phone)}">📞 ${esc(b.phone)}</a>`:''}${(b.whatsapp||b.phone)?`<a class="btn btn-outline" target="_blank" rel="noopener" href="https://wa.me/977${esc(String(b.whatsapp||b.phone).replace(/\D/g,'').slice(-10))}">💬 WhatsApp</a>`:''}</div><p class="muted">Paid/Featured हुनु र Verified हुनु फरक status हुन् ।</p></div></div>`;openModal('profileModal');}
function openModal(id){$('#'+id)?.classList.add('open');document.body.style.overflow='hidden'}function closeModal(id){$('#'+id)?.classList.remove('open');document.body.style.overflow=''}
let regStep=1,reg={plan:'basic'};function setStep(n){regStep=n;$$('.reg-step').forEach((x,i)=>x.hidden=i!==n-1);$$('.step').forEach((x,i)=>x.classList.toggle('active',i===n-1));$('#regBack').hidden=n===1;$('#regNext').textContent=n===4?'Submit for Review':'Next';}
function collect(){$$('#businessForm [name]').forEach(e=>reg[e.name]=e.type==='checkbox'?e.checked:e.value);const checked=$$('input[name="categoryPick"]:checked').map(x=>x.value);reg.categories=checked;}
async function nextReg(){collect();if(regStep===1&&(!reg.name||!reg.mobile)){alert('Business Name र Mobile आवश्यक छ ।');return}if(regStep===2&&!reg.categories.length){alert('कम्तीमा एउटा Category छान्नुहोस् ।');return}if(regStep<4){setStep(regStep+1);return}const r=await api('registerBusiness',{business:reg});alert(r.ok?'Registration received. Verification/review पछि मात्र public listing हुनेछ ।':'Submit failed: '+(r.message||''));if(r.ok){closeModal('businessModal');$('#businessForm').reset();regStep=1;reg={plan:'basic'};setStep(1);}}
function buildRegister(){const cats=D.masterCategories.flatMap(c=>c.subs);$('#categoryPicks').innerHTML=cats.map(x=>`<label><input type="checkbox" name="categoryPick" value="${esc(x)}"> ${esc(x)}</label>`).join('<br>');$('#plans').innerHTML=D.plans.map(p=>`<button type="button" class="plan ${p.id==='basic'?'selected':''}" data-plan="${p.id}"><strong>${p.name}</strong><div class="price">${p.price?'रु '+p.price.toLocaleString():'Free'}</div><div class="muted">/${p.period}</div><ul>${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul></button>`).join('');$$('[data-plan]').forEach(x=>x.onclick=()=>{$$('[data-plan]').forEach(y=>y.classList.remove('selected'));x.classList.add('selected');reg.plan=x.dataset.plan});}
function nearMe(){if(!navigator.geolocation){alert('यो browser मा location उपलब्ध छैन ।');return}$('#location').value='स्थान पत्ता लगाउँदै...';navigator.geolocation.getCurrentPosition(pos=>{$('#location').value=`${pos.coords.latitude.toFixed(5)},${pos.coords.longitude.toFixed(5)}`;},()=>{$('#location').value='';alert('Location permission दिनुहोस् वा स्थान आफैं लेख्नुहोस् ।')},{timeout:8000});}
function init(){renderCategories();buildRegister();$('#searchBtn').onclick=doSearch;$('#q').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});$('#location').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});$('#nearMeBtn').onclick=nearMe;$('#sortResults').onchange=sortAndRender;$$('[data-search]').forEach(x=>x.onclick=()=>{$('#q').value=x.dataset.search;doSearch()});$$('[data-open-register]').forEach(x=>x.onclick=()=>openModal('businessModal'));$$('[data-close]').forEach(x=>x.onclick=()=>closeModal(x.dataset.close));$('#regNext').onclick=nextReg;$('#regBack').onclick=()=>setStep(Math.max(1,regStep-1));$('#policeBtn').onclick=()=>window.open(C.OFFICIAL_POLICE_URL,'_blank','noopener');$('#sosBtn').onclick=()=>openModal('sosModal');$('#sendSOS').onclick=()=>alert('Emergency routing अर्को update मा verified responder workflow सँग जोडिनेछ । Official emergency calls प्राथमिक हुन् ।');doSearch();}
document.addEventListener('DOMContentLoaded',init);
